<?php
/**
 * @file
 * Relationship of fields
 */

/**
 * Implements hook_form_alter().
 */
function dc_relationship_of_fields_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'tasks_node_form') {
    $form['field_section_task'][LANGUAGE_NONE]['#ajax'] = array(
      'callback' => 'dc_relationship_of_fields_task_topic_form',
      'wrapper' => 'topic-list',
    );
    $form['field_task_topic'][LANGUAGE_NONE]['#prefix'] = '<div id="topic-list">';
    $form['field_task_topic'][LANGUAGE_NONE]['#suffix'] = '</div>';
    $form['field_task_topic'][LANGUAGE_NONE]['#default_value'] = NULL;

    $tid_section = '';
    if (isset($form_state['values']['field_section_task'][LANGUAGE_NONE][0]['target_id'])) {
      $tid_section = $form_state['values']['field_section_task'][LANGUAGE_NONE][0]['target_id'];
    }
    $topics = dc_relationship_of_fields_get_topics_options($tid_section);

    $form['field_task_topic'][LANGUAGE_NONE]['#options'] = $topics;
  }

  return $form;
}

/**
 * Implements hook_update_N().
 */
function dc_relationship_of_fields_update_7100(&$sandbox) {
  $vocabulary_sections = taxonomy_vocabulary_machine_name_load('sections');

  $term_drupal_7 = new stdClass();
  $term_drupal_7->name = 'Drupal 7';
  $term_drupal_7->vid = $vocabulary_sections->vid;
  taxonomy_term_save($term_drupal_7);
}

/**
 * Implements hook_update_N().
 */
function dc_relationship_of_fields_update_7101(&$sandbox) {
  $vocabulary_task_topic = taxonomy_vocabulary_machine_name_load('task_topic');
  $term_drupal_7 = array_shift(taxonomy_term_load_multiple(NULL, array('name' => 'Drupal 7')));
  $topic_terms = taxonomy_term_load_multiple(NULL, array('vid' => $vocabulary_task_topic->vid));

  foreach ($topic_terms as $topic_term) {
    $topic_term->field_section['und'][0]['target_id'] = $term_drupal_7->tid;
    taxonomy_term_save($topic_term);
  }
}

/**
 * Implements hook_update_N().
 */
function dc_relationship_of_fields_update_7106(&$sandbox) {
  $term_drupal_7 = array_shift(taxonomy_term_load_multiple(NULL, array('name' => 'Drupal 7')));
  $tasks_nodes = node_load_multiple(NULL, array('type' => 'tasks'));

  foreach ($tasks_nodes as $tasks_node) {
    $tasks_node->field_section_task[LANGUAGE_NONE][0]['target_id'] = $term_drupal_7->tid;
    node_save($tasks_node);
  }
}

/**
 * Implements hook_update_N().
 */
function dc_relationship_of_fields_update_7107(&$sandbox) {
  $employees = node_load_multiple(NULL, array('type' => 'employees'));
  $term_drupal_7 = array_shift(taxonomy_term_load_multiple(NULL, array('name' => 'Drupal 7')));

  foreach ($employees as $employee) {
    $employee->field_sections_employees[LANGUAGE_NONE][0]['target_id'] = $term_drupal_7->tid;
    node_save($employee);
  }
}

/**
 * Return select options of topics relations with sections.
 */
function dc_relationship_of_fields_get_topics_options($tid_section) {
  $vocabulary = taxonomy_vocabulary_machine_name_load('task_topic');

  $query = db_select('taxonomy_term_data', 'ttd');
  $query->fields('ttd', array('tid', 'name'));
  $query->innerJoin('field_data_field_section', 'fdfs', 'ttd.tid = fdfs.entity_id');
  $query->condition('ttd.vid', $vocabulary->vid);
  $query->condition('fdfs.field_section_target_id', $tid_section);

  $topics = $query->execute()->fetchAll();

  $options = array();
  if (!empty($topics)) {
    foreach ($topics as $topic) {
      $options[$topic->tid] = $topic->name;
    }
  }

  return $options;
}

/**
 * Return form field_task_topic
 */
function dc_relationship_of_fields_task_topic_form($form, &$form_state) {
  return $form['field_task_topic'];
}
