<?php
/**
 * @file
 * The module allows change task status
 */

/**
 * Implements hook_menu().
 */
function dc_changer_menu() {
 drupal_add_library('system', 'drupal.ajax');

 $items['change-status/nojs/%'] = array(
  'page callback' => '_dc_changer_update',
  'page arguments' => array(1, 2),
  'access arguments' => array('permission name'),
  'type' => MENU_CALLBACK,
 );

 $items['change-status/ajax/%'] = array(
   'delivery callback' => 'ajax_deliver',
  ) + $items['change-status/nojs/%'];

 return $items;
}

/**
 * Function creates and returns ajax_commands to change status for assigned tasks.
 */
function _dc_changer_update($ajax, $nid) {
 $is_ajax = $ajax === 'ajax';

 $node = node_load($nid);
 $node->field_status['und'][0]['tid'] = 1;
 node_save($node);

$target_status = taxonomy_term_load(1);

 if ($is_ajax) {
  $commands = array();
  $commands[] = ajax_command_remove(".control-actions-link[data-nid=$nid]");
  $commands[] = ajax_command_html(".assigned-task-status[data-nid=$nid]", $target_status->name);
  return array(
   '#type' => 'ajax',
   '#commands' => $commands,
  );
 }

}
