<?php
/**
 * @file
 * Auto complete assigned tasks title
 */

/**
 * Implements hook_form_alter().
 */
function dc_autocomplete_assigned_tasks_title_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'assigned_tasks_node_form') {
    drupal_add_js(drupal_get_path('module', 'dc_autocomplete_assigned_tasks_title') . '/dc_autocomplete_assigned_tasks_title.js');

    $form['field_nid_task']['#attributes']['class'][] = 'field_nid_task';
    $form['field_nid_employee']['#attributes']['class'][] = 'field_nid_employee';
    $form['title']['#attributes']['class'][] = 'title';
  }

  return $form;
}
